### PR TITLE
Implement Child Process & Dynamic GraphQL Data Loading

### PR DESCRIPTION
**Pull request by mccallofthewild**
# Summary
Adds dynamic data loading and frees up main thread by delegating compute to child process. 

# Important 
 All getter methods that utilize Processed Data have been moved to `js/process.childprocess.js` under `BackgroundProcessor#actions`. 

# Architecture
## Loaders (`js/loaders/*`)
* Respectively pull Liquidity Miner & Validator snapshot data from GraphQL endpoint
* Uses existing environment secrets & the `dotenv` module has been implemented. Should work with zero config in dev env

## Child Process (`js/process.childprocess.js`)
* Reloads & Reprocesses snapshots on a 10 minute loop
* Provides action dispatcher interface for Main Process to interact with processed data without copying it over
* To load local data instead (for test/development), set the `LOCAL_SNAPSHOT_DEV_MODE=enabled` in your `.env`

## Processing Handler (`js/processing-handler.js`)
* Forks the Child Process
* Provides `#dispatch` method by which the express router endpoints can interact with processed data inside of Child Process

# Progress
* Live snapshot data
* No longer blocking main thread 

# Limitations 
* Still limited by the `process` functions' compute time 
  * Processed result cannot be transferred back to the main thread (see next bullet point), so `process` fns proceed to block the I/O of action dispatcher in child process
* Node can't share memory w/o serializing.  Our **400MB+** JS object takes an eternity and a lot of resources to serialize.
* Memory Limit: I assume `--max-old-space-size=4096` was set with respect to the production environment. Typically plenty, but most of the issues I've faced have been memory related. Is increasing this limit on the table? @intl-man 

# Opportunities 
* Revolving Child Processes: 
  * e.g.
    *  Move Update Interval to Parent Process
    *  Create multiple Processing Handlers (`./processing-handler.js`) and toggle between them as they take turns loading & processing each round of new data. 
      * One Processed Result is always available while the other is next is being computed
  * Never stuck waiting on a blocked thread. (after initial load)
  * Would require more memory, as the Child Processes need to hold their Processing Results simultaneously.

### CODE REVIEW

**Comment by musnit** [comment]
max-old-space-size=4096 yeh can increase it - im sure we can scale up to 64gb+ - the main problem with going higher is if your dev machine is limited (mine is only 8gb :(, but could move to do dev on an aws remote box too if we need more)

**Comment by 59023g** [comment]
Looks good. What's the initial load sequence? I have `LOCAL_SNAPSHOT_DEV_MODE=disabled` and the proper ENV keys, yet the snapshots are not loaded. 
```
TypeError: Cannot read property 'snapshots_new' of undefined
    at exports.getProcessedLMData (/Users/osso/sif/cryptoeconomics/js/server/process.js:21:39)
    at BackgroundProcessor.reloadAndReprocessOnLoop (/Users/osso/sif/cryptoeconomics/js/server/process.childprocess.js:115:24)
```

**Comment by mccallofthewild** [comment]
> Looks good. What's the initial load sequence? I have `LOCAL_SNAPSHOT_DEV_MODE=disabled` and the proper ENV keys, yet the snapshots are not loaded.
> 
> ```
> TypeError: Cannot read property 'snapshots_new' of undefined
>     at exports.getProcessedLMData (/Users/osso/sif/cryptoeconomics/js/server/process.js:21:39)
>     at BackgroundProcessor.reloadAndReprocessOnLoop (/Users/osso/sif/cryptoeconomics/js/server/process.childprocess.js:115:24)
> ```

Have you run the scripts: `refresh-lm-snapshot` & `refresh-vs-snapshot` recently?

**Comment by mccallofthewild** [comment]
And you've run `yarn install`?

**Comment by 59023g** [comment]
> And you've run `yarn install`?

Yes

**Review by 59023g — APPROVED** [review]

**Comment by musnit** [comment]
@mccallofthewild if a web request comes in while a new snapshot is being processed, what will happen to it?

**Comment by mccallofthewild** [comment]
@musnit That can't happen because the event loop is blocked by the processing functions. The alternative to multiple processes would be making the processing functions async and waiting for the event loop between iterations with `await new Promise(r => setImmediate(r))`. But it's not plug-and-play because most of the processing code is inside callbacks, which would mean a lot of rewriting

**Comment by musnit** [comment]
> @musnit That can't happen because the event loop is blocked by the processing functions.
> 

well, what happens to the web request? will it timeout/error? will it stall and likely be fulfilled after 15 seconds or so? or?

> It would be possible if we used the alternative to multiple processes would be making the processing functions async and waiting for the event loop between iterations with `await new Promise(r => setImmediate(r))`. But it's not plug-and-play because most of the processing code is inside callbacks, which would mean a lot of rewriting

yeh or something like this may be simpler, though seems risky:
 - fork new child process every 5min, get it to get latest data, do all processing, etc
 - when its done, it responds to main process saying its ready
 on main process:
  - server responses from old child
  - when new child is ready, start serving responses from new child, and kill old child

**Comment by mccallofthewild** [comment]
@musnit Ah, you mean if someone hits our API. I thought you meant when the GraphQL response data comes in. 

Yeah, our express server is running on the main process, unblocked, so it can respond immediately. As long as they don't kill the request on the client, it will eventually respond once the child process has the data ready.

First idea is what this branch currently does. 

Second idea is very similar to what I'm working on. 👍

**Pull request merged**
